### ISSUE TITLE
All fields are treated as regular text fields; option lists don't populate

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/civicrm_entity#196]
To illustrate the issue, consider these two screenshots from D7/D8:

**D7**:
![Selection_721](https://user-images.githubusercontent.com/1796012/69282395-389e2e00-0bb8-11ea-947f-20b2964cab70.png)

**D8:**
![Selection_720](https://user-images.githubusercontent.com/1796012/69282404-405dd280-0bb8-11ea-8153-ace1da9f49f7.png)

The D7 Views knows that this is an option list and not a text field.  It also displays the label and not the primary key from `civicrm_state_province`.

In addition to not displaying as a select box, an exposed filter doesn't work unless you enter the key of the value - e.g. searching on country, you must enter `1228` instead of `United States`.

Knowledge about data types extends to other areas as well - e.g. I can pull the Image URL from `civicrm_contact`, but it displays as a plaintext URL, it's not recognized as an image data type, so e.g. I can't use image styles on it.

**Comment by mglaman** [comment]
To help scope the issue, this is for the Views integration?

The Views module isn't aware of available field values. This makes sense, since we did not provide any custom Views handler plugins for fields or filters. Any filters with list values have a custom handler that queries for the values (bundle filter, for example.)

We'll need to make sure proper fields use the `in_operator` and specify a `options callback` value.

From \Drupal\views\Plugin\views\filter\InOperator::getValueOptions

```
    if (isset($this->definition['options callback']) && is_callable($this->definition['options callback'])) {
      if (isset($this->definition['options arguments']) && is_array($this->definition['options arguments'])) {
        $this->valueOptions = call_user_func_array($this->definition['options callback'], $this->definition['options arguments']);
      }
      else {
        $this->valueOptions = call_user_func($this->definition['options callback']);
      }
    }
```

**Comment by mglaman** [comment]
I found the problem \Drupal\civicrm_entity\CivicrmEntityViewsData::processViewsDataForListString existed but not \Drupal\civicrm_entity\CivicrmEntityViewsData::processViewsDataForListInteger.
